# Generated by Django 4.2.2 on 2023-10-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_remove_order_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
