# Generated by Django 4.2.2 on 2023-10-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_account_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
