# Generated by Django 4.2.2 on 2023-10-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_order_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.FloatField(blank=True),
        ),
    ]
